version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: wog
    ports:
      - "30000:30000"
    environment:
      FLASK_ENV: production
    networks:
      - wog_network

  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    image: wog2
    environment:
      - SELENIUM_DRIVER_URI=http://selenium:4444
      - SELENIUM_DRIVER_CAPABILITIES="browserName=chrome"
    depends_on:
      - web
    networks:
      - wog_network

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - wog_network

networks:
  wog_network:
    driver: bridge